apiVersion: v1
kind: Service
metadata:
  labels:
    app: nebula-metad
  name: neubla-metad
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  publishNotReadyAddresses: true
  clusterIP: None
  ports:
  - name: thrift
    port: 44500
  - name: raft
    port: 44501
  - name: http
    port: 11000
  - name: http2
    port: 11002
  selector:
    app: nebula-metad
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nebula-metad
  labels:
    app: nebula
spec:
  serviceName: nebula-metad
  replicas: 3
  selector:
    matchLabels:
      app: nebula-metad
  template:
    metadata:
      labels:
        app: nebula-metad
    spec:
#      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - nebula-metad
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 60
      hostname: meta.nebula.services
      containers:
      - name: nebula-metad
        image: vesoft/nebula-metad:nightly
        imagePullPolicy: Always
        ports:
        - containerPort: 45500
          name: thrift
        - containerPort: 45501
          name: raft
        - containerPort: 11000
          name: http
        - containerPort: 11002
          name: http2
        command: 
          - "/bin/bash"
          - "-ecx"
          - "exec /usr/local/nebula/bin/nebula-metad --flagfile=/usr/local/nebula/etc/nebula-metad.conf --daemonize=false --local_ip=$(hostname -i) --ws_ip=0.0.0.0"
        livenessProbe:
          httpGet:
            path: /status
            port: 11000
          initialDelaySeconds: 30
          timeoutSeconds: 5          
        volumeMounts:
        - name: data
          mountPath: /usr/local/nebula/data/
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: data
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
